---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mixer-config
data:
  globalconfig.yml: |-
    subject: "namespace:ns"
    revision: "2022"
    adapters:
      - name: default
        kind: quotas
        impl: memQuota
        params:
      - name: default
        impl: stdioLogger
        params:
          logStream: 0 # STDERR
      - name: prometheus
        kind: metrics
        impl: prometheus
        params:
      - name: default
        impl: denyChecker
  serviceconfig.yml: |-
    subject: namespace:ns
    revision: "2022"
    rules:
            #- selector: service.name == “*”
            #- selector: service.name == "myservice"
    - selector: true
      aspects:
      - kind: quotas
        params:
      - kind: metrics
        adapter: prometheus
        params:
          metrics:
          - descriptor_name: request_count
            # we want to increment this counter by 1 for each unique (source, target, service, method, response_code) tuple
            value: "1"
            labels:
              source: source.service | "unknown"
              target: target.service | "unknown"
              service: api.name | "unknown"
              method: api.method | "unknown"
              response_code: response.http.code | 200
          - descriptor_name:  request_latency
            value: response.latency | "0ms"
            labels:
              source: source.service | "unknown"
              target: target.service | "unknown"
              service: api.name | "unknown"
              method: api.method | "unknown"
              response_code: response.http.code | 200
---
